//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodatra.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sodatra.Content.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodePPM.
        /// </summary>
        internal static string CodePPMText1 {
            get {
                return ResourceManager.GetString("CodePPMText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodePPm.
        /// </summary>
        internal static string CodePPMText2 {
            get {
                return ResourceManager.GetString("CodePPMText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NINEA.
        /// </summary>
        internal static string CodePPMText3 {
            get {
                return ResourceManager.GetString("CodePPMText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CcdePPM.
        /// </summary>
        internal static string CodePPMText4 {
            get {
                return ResourceManager.GetString("CodePPMText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnaissementallLTA.
        /// </summary>
        internal static string ConnaissementText1 {
            get {
                return ResourceManager.GetString("ConnaissementText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnaissemcntouLTA.
        /// </summary>
        internal static string ConnaissementText2 {
            get {
                return ResourceManager.GetString("ConnaissementText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connaissemenl.
        /// </summary>
        internal static string ConnaissementText3 {
            get {
                return ResourceManager.GetString("ConnaissementText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connaissement.
        /// </summary>
        internal static string ConnaissementText4 {
            get {
                return ResourceManager.GetString("ConnaissementText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteneurs.
        /// </summary>
        internal static string ContainersText1 {
            get {
                return ResourceManager.GetString("ContainersText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centoneurs.
        /// </summary>
        internal static string ContainersText2 {
            get {
                return ResourceManager.GetString("ContainersText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteneurs.
        /// </summary>
        internal static string ContainersText3 {
            get {
                return ResourceManager.GetString("ContainersText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteneurs.
        /// </summary>
        internal static string ContainersText4 {
            get {
                return ResourceManager.GetString("ContainersText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endevise.
        /// </summary>
        internal static string endevise {
            get {
                return ResourceManager.GetString("endevise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enFCFA.
        /// </summary>
        internal static string enFCFA {
            get {
                return ResourceManager.GetString("enFCFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturedesmarchandiscs.
        /// </summary>
        internal static string NatureofGoodsText1 {
            get {
                return ResourceManager.GetString("NatureofGoodsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturedesmarchandises.
        /// </summary>
        internal static string NatureofGoodsText2 {
            get {
                return ResourceManager.GetString("NatureofGoodsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturedesmarchandis.
        /// </summary>
        internal static string NatureofGoodsText3 {
            get {
                return ResourceManager.GetString("NatureofGoodsText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturcdesmarchandiscs.
        /// </summary>
        internal static string NatureofGoodsText4 {
            get {
                return ResourceManager.GetString("NatureofGoodsText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaturedeI&apos;emballage.
        /// </summary>
        internal static string NatureofPackagingText1 {
            get {
                return ResourceManager.GetString("NatureofPackagingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaturedeI&apos;emballage.
        /// </summary>
        internal static string NatureofPackagingText2 {
            get {
                return ResourceManager.GetString("NatureofPackagingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaturedeI&apos;emballage.
        /// </summary>
        internal static string NatureofPackagingText3 {
            get {
                return ResourceManager.GetString("NatureofPackagingText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaturedeI&apos;emballage.
        /// </summary>
        internal static string NatureofPackagingText4 {
            get {
                return ResourceManager.GetString("NatureofPackagingText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.Description.
        /// </summary>
        internal static string setString1 {
            get {
                return ResourceManager.GetString("setString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endeviseenFCFA.
        /// </summary>
        internal static string setString2 {
            get {
                return ResourceManager.GetString("setString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeSH.
        /// </summary>
        internal static string setString3 {
            get {
                return ResourceManager.GetString("setString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitFOBatteste.
        /// </summary>
        internal static string UnitFOBatteste {
            get {
                return ResourceManager.GetString("UnitFOBatteste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsageQuantite.
        /// </summary>
        internal static string UsageQuantite {
            get {
                return ResourceManager.GetString("UsageQuantite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeurdereference.
        /// </summary>
        internal static string valeurdereference {
            get {
                return ResourceManager.GetString("valeurdereference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendeur(.
        /// </summary>
        internal static string VendorText1 {
            get {
                return ResourceManager.GetString("VendorText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vcndeur(.
        /// </summary>
        internal static string VendorText2 {
            get {
                return ResourceManager.GetString("VendorText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vend~~Jr(.
        /// </summary>
        internal static string VendorText3 {
            get {
                return ResourceManager.GetString("VendorText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendcur(.
        /// </summary>
        internal static string VendorText4 {
            get {
                return ResourceManager.GetString("VendorText4", resourceCulture);
            }
        }
    }
}
