//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodatra.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sodatra.Content.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endevise.
        /// </summary>
        internal static string endevise {
            get {
                return ResourceManager.GetString("endevise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enFCFA.
        /// </summary>
        internal static string enFCFA {
            get {
                return ResourceManager.GetString("enFCFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.Description.
        /// </summary>
        internal static string setString1 {
            get {
                return ResourceManager.GetString("setString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endeviseenFCFA.
        /// </summary>
        internal static string setString2 {
            get {
                return ResourceManager.GetString("setString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeSH.
        /// </summary>
        internal static string setString3 {
            get {
                return ResourceManager.GetString("setString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniteFOBatteste.
        /// </summary>
        internal static string uniteFOBatteste {
            get {
                return ResourceManager.GetString("uniteFOBatteste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsageQuantite.
        /// </summary>
        internal static string UsageQuantite {
            get {
                return ResourceManager.GetString("UsageQuantite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeurdereference.
        /// </summary>
        internal static string valeurdereference {
            get {
                return ResourceManager.GetString("valeurdereference", resourceCulture);
            }
        }
    }
}
