//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodatra
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SodatraEntities : DbContext
    {
        public SodatraEntities()
            : base("name=SodatraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_SodatraDetails> Table_SodatraDetails { get; set; }
        public virtual DbSet<Table_SodatraItemDetails> Table_SodatraItemDetails { get; set; }
    }
}
