//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodatra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_SodatraItemDetails
    {
        public long SodatraItemId { get; set; }
        public long SodatraId { get; set; }
        public Nullable<int> No { get; set; }
        public string Description { get; set; }
        public string HSCode { get; set; }
        public string Usage { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> FOBAttestedInCurrency { get; set; }
        public Nullable<decimal> ReferenceValueInFCFA { get; set; }
    
        public virtual Table_SodatraDetails Table_SodatraDetails { get; set; }
    }
}
